# Generated by Django 4.1.2 on 2023-03-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_avatar_alter_profile_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/diallo/image/upload/v1647154137/8_fncc3c.jpg', upload_to='developers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/diallo/image/upload/v1647154140/4-big_sd6hps.jpg', upload_to='developers/'),
        ),
    ]
