# Generated by Django 4.1.2 on 2023-03-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_alter_feed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
