# Generated by Django 4.1.2 on 2023-03-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0014_alter_feed_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='cover_image',
            new_name='feed_image',
        ),
    ]
